
CREATE TABLE IF NOT EXISTS payment_recovery_token(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cart_id BIGINT, session_id VARCHAR(64), token VARCHAR(64) UNIQUE,
  expires_at TIMESTAMP, used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);