
CREATE TABLE ndr_token(
  id BIGINT PRIMARY KEY AUTO_INCREMENT, order_no VARCHAR(64), token VARCHAR(64) UNIQUE,
  expires_at TIMESTAMP, used BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);