
CREATE TABLE permission(id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(64) UNIQUE);
CREATE TABLE role_permission(id BIGINT PRIMARY KEY AUTO_INCREMENT, role VARCHAR(32), perm_code VARCHAR(64));
CREATE TABLE user_mfa_fields(id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT UNIQUE, mfa_secret VARCHAR(64), mfa_enabled BOOLEAN DEFAULT FALSE);