INSERT INTO product (
    slug,
    title,
    description_html,
    hero_image_url,
    price_paise,
    mrp_paise,
    category_slug,
    tags,
    search_text,
    in_stock,
    badge
) VALUES
  (
    'gongura-pandumirchi',
    'Gongura Pandumirchi Pickle',
    '<p>Sun-dried red chillies pickled with tangy gongura leaves and cold-pressed oils.</p>',
    '/assets/images/gongura_pandumirchi_670x.jpg',
    32900,
    35900,
    'veg-pickles',
    'pickle,gongura,chilli,veg,spicy',
    'Gongura pandumirchi chilli pickle tangy spicy vegetarian favourite handcrafted',
    1,
    'Hot'
  ),
  (
    'budida-gummadikaya',
    'Budida Gummadikaya Pickle',
    '<p>Rare ash gourd pickle slow-cooked with jaggery and aromatic Andhra spice blends.</p>',
    '/assets/images/ash_gourd_670x.jpg',
    31900,
    34900,
    'veg-pickles',
    'pickle,ash-gourd,sweet,veg',
    'Budida gummadikaya ash gourd pickle mildly sweet micro batch heritage recipe',
    1,
    NULL
  ),
  (
    'kothimeera-pickle',
    'Kothimeera Pickle',
    '<p>Fresh coriander pickle tempered with garlic and sesame for a bright, herby punch.</p>',
    '/assets/images/kothimeera_670x.jpg',
    29900,
    32900,
    'veg-pickles',
    'pickle,coriander,kothimeera,veg,fresh',
    'Kothimeera coriander pickle fresh and zingy tempered with sesame seeds traditional',
    1,
    NULL
  ),
  (
    'gongura-mutton',
    'Gongura Mutton Pickle',
    '<p>Slow-cooked mutton chunks steeped in gongura leaves, garlic and fiery Andhra spices.</p>',
    '/assets/images/mutton_gongura.jpg',
    54900,
    58900,
    'non-veg-pickles',
    'pickle,non-veg,gongura,mutton,best-seller',
    'Gongura mutton pickle hearty non veg bestseller slow cooked tender meats',
    1,
    'Chef’s pick'
  ),
  (
    'natu-kodi',
    'Natu Kodi Pickle',
    '<p>Farm-raised country chicken pickle simmered in sesame oil with pepper, jeera and cloves.</p>',
    '/assets/images/chicken.jpg',
    52900,
    56900,
    'non-veg-pickles',
    'pickle,non-veg,chicken,natu-kodi,spicy',
    'Natu kodi country chicken pickle bold spices slow simmered sesame oil Andhra style',
    1,
    NULL
  ),
  (
    'prawns',
    'Royal Prawns Pickle',
    '<p>Succulent prawns coated in chilli-garlic masala and sun-cured for a coastal umami kick.</p>',
    '/assets/images/prawns.jpg',
    57900,
    61900,
    'non-veg-pickles',
    'pickle,non-veg,seafood,prawns,spicy',
    'Prawns pickle coastal favourite chilli garlic masala rich umami seafood kick',
    1,
    'Limited batch'
  ),
  (
    'crab-pickle',
    'Spiced Crab Pickle',
    '<p>Handpicked crab meat cooked with stone-ground masalas and sealed with gingelly oil.</p>',
    '/assets/images/fish.jpg',
    58900,
    62900,
    'non-veg-pickles',
    'pickle,non-veg,seafood,crab,heritage',
    'Spiced crab pickle indulgent seafood delicacy slow cooked stone ground masala',
    1,
    NULL
  ),
  (
    'karivepaku-podi',
    'Karivepaku Podi',
    '<p>Iron-rich curry leaf podi roasted with sesame, lentils and aromatic ghee tempering.</p>',
    '/assets/images/karivepaku_670x.jpg',
    19900,
    22900,
    'podi',
    'podi,karivepaku,curry-leaf,protein',
    'Karivepaku podi curry leaf blend protein rich roasted lentils iron boost',
    1,
    'Daily staple'
  ),
  (
    'sambar-mix',
    'Homestyle Sambar Mix',
    '<p>Classic sambar masala with roasted dal, coriander seeds and Byadgi chillies.</p>',
    '/assets/images/podi.jpg',
    17900,
    20900,
    'podi',
    'podi,sambar,mix,instant',
    'Homestyle sambar mix quick cooking masala roasted dal coriander seeds byadgi chilli',
    1,
    NULL
  ),
  (
    'flax-seed-podi',
    'Flax Seed Podi',
    '<p>Omega-rich flax seeds toasted with garlic, dried coconut and red chillies.</p>',
    '/assets/images/flax_670x.jpg',
    18900,
    21900,
    'podi',
    'podi,flax,healthy,omega',
    'Flax seed podi omega rich toasted seeds garlic coconut red chilli wholesome',
    1,
    'Healthy pick'
  ),
  (
    'bellam-gavvalu',
    'Bellam Gavvalu',
    '<p>Crispy gavvalu coated in glossy jaggery caramel with hints of cardamom.</p>',
    '/assets/images/dry-fruit_670x.jpg',
    24900,
    27900,
    'snacks-sweets',
    'snack,sweet,gavvalu,jaggery',
    'Bellam gavvalu jaggery glazed crunchy shells festive sweet snack classic',
    1,
    'Festive special'
  ),
  (
    'ribbon-pakodi',
    'Ribbon Pakodi',
    '<p>Crunchy ribbon murukku made with rice flour, besan and aromatic chilli-garlic tempering.</p>',
    '/assets/images/raagi-murukulu.jpg',
    22900,
    25900,
    'snacks-sweets',
    'snack,savoury,ribbon,pakodi',
    'Ribbon pakodi crunchy savoury snack rice flour besan chilli garlic tempering',
    1,
    NULL
  ),
  (
    'badam-halwa',
    'Badam Halwa',
    '<p>Rich almond halwa slow-cooked in ghee with saffron, cardamom and condensed milk.</p>',
    '/assets/images/dry-fruit_670x.jpg',
    39900,
    44900,
    'snacks-sweets',
    'sweet,badam,halwa,festive',
    'Badam halwa decadent almond dessert ghee slow cooked saffron festive favourite',
    1,
    'Bestseller'
  )
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  description_html = VALUES(description_html),
  hero_image_url = VALUES(hero_image_url),
  price_paise = VALUES(price_paise),
  mrp_paise = VALUES(mrp_paise),
  category_slug = VALUES(category_slug),
  tags = VALUES(tags),
  search_text = VALUES(search_text),
  in_stock = VALUES(in_stock),
  badge = VALUES(badge);
